### ISSUE TITLE
the wallet endpoint is equal to createWallet, but i can access a wallet endpoint method by createTrade, how

### ISSUE THREAD

**Issue by AlberoPazzo** [binance/binance-connector-java#37]
i tried to do the following in a class that i called BinanceConnection:

```
//creation of client with spot Test Network
14-                I_UserConnection connect = new TestUser(); 
15-                SpotClientImpl client = connect.createConnection();
16-                String result = ""; 
17-                
18-                try {
19-                       LinkedHashMap<String,Object> parameters = new LinkedHashMap<>();
                          /*
                          the line below is supposed to return the wallet coins info
                          and to be the same as the binance api Wallet -> All coins' information (USER_DATA)
                          */
20-                       result = client.createWallet().coinInfo(parameters); 
21-                       logger.info(result);
22-                   }
23-                   catch (Ex1 e) { . . . }
26-                   catch (Ex2 e) { . . . }
```
the result of the code is the following

```
--- exec-maven-plugin:3.0.0:exec (default-cli) @ projecttest1 ---
2022-06-12 20:38:18.847[1655059098847] | INFO  | main       | c.b.c.client.utils.RequestHandler    - GET https://testnet.binance.vision/sapi/v1/capital/config/getall?timestamp=1655059097707&signature=(HMAC SHA256)
2022-06-12 20:38:21.867[1655059101867] | ERROR | main       | c.m.m.BinanceConnection              - fullErrMessage:  
errMessage: null 
errCode: 0 
HTTPStatusCode: 404
com.binance.connector.client.exceptions.BinanceClientException: 
	at com.binance.connector.client.utils.ResponseHandler.handleErrorResponse(ResponseHandler.java:63)
	at com.binance.connector.client.utils.ResponseHandler.handleResponse(ResponseHandler.java:32)
	at com.binance.connector.client.utils.RequestHandler.sendApiRequest(RequestHandler.java:53)
	at com.binance.connector.client.utils.RequestHandler.sendSignedRequest(RequestHandler.java:77)
	at com.binance.connector.client.impl.spot.Wallet.coinInfo(Wallet.java:58)
	at com.mycompany.mavenproject1test.BinanceConnection.main(BinanceConnection.java:20)

```
now if i try differently using this:
`result = client.createTrade().account(parameters);`
it gives me the wallet coins info, why is that?

**Comment by chairz** [comment]
You received a http status of 404 which means that the url you are querying is invalid. Check if you have passed in your own url when initializing `SpotClientImpl`

**Comment by AlberoPazzo** [comment]
if that was the case then changing method wouldn't fix it but it does, then there is something wrong with the method

**Comment by AlberoPazzo** [comment]
btw im using the test net is there any difference or something that doesnt work for the test network?

**Comment by chairz** [comment]
Closed due to inactivity.
