### ISSUE TITLE
Error: Hostname api.binance.com not verified (no certificates)

### ISSUE THREAD

**Issue by kunalransing** [binance/binance-connector-java#75]
Hi,
I am using binance-connector-java version 1.6.0 in spring boot 2.7.0 & JDK 11
```
		<dependency>
		    <groupId>io.github.binance</groupId>
		    <artifactId>binance-connector-java</artifactId>
		    <version>1.6.0</version>
		</dependency>
```
Sometime I am getting below issues while calling api/v3/ticker/price.

```
BinanceService_loadExchangeRates: Request={symbols=["TRXBTC","TRXETH","ETHUSDT","ETHBTC","TRXUSDT","BTCUSDT"]}
2023-02-16 12:44:23.855[1676551463855] | INFO  | taskExecutor-1 | c.b.c.client.utils.RequestHandler    - GET https://api.binance.com/api/v3/ticker/price?symbols=%5B%22TRXBTC%22%2C%22TRXETH%22%2C%22ETHUSDT%22%2C%22ETHBTC%22%2C%22TRXUSDT%22%2C%22BTCUSDT%22%5D
Error:[ResponseHandler] **OKHTTP Error: Hostname api.binance.com not verified (no certificates)**
com.binance.connector.client.exceptions.BinanceConnectorException: [ResponseHandler] OKHTTP Error: Hostname api.binance.com not verified (no certificates)
	at com.binance.connector.client.utils.ResponseHandler.handleResponse(ResponseHandler.java:41)
	at com.binance.connector.client.utils.RequestHandler.sendApiRequest(RequestHandler.java:53)
	at com.binance.connector.client.utils.RequestHandler.sendPublicRequest(RequestHandler.java:58)
	at com.binance.connector.client.impl.spot.Market.tickerSymbol(Market.java:256)
```
Please help me to fix issue.
Thanks.

**Comment by aisling-2** [comment]
This seems to be _OKHTTP library_ failing to verify the api.binance.com's SSL certificate.
When encountering this error, you could:
- Retry the request;
- (or) You can download the SSL certificate for api.binance.com and add it to your `truststore`, by using `keytool` command (example below):
`keytool -import -alias binance -file downloaded_binance.crt -keystore truststore.jks`

**Comment by aisling-2** [comment]
Closing the Issue for now due to inactivity, if there's further questions, please feel free to reopen.
