### ISSUE TITLE
Websocket got java.io.InterruptedIOException: executor rejected after second time invoke

### ISSUE THREAD

**Issue by jasonyl13579** [binance/binance-connector-java#90]
Hi, I tried to wrap the following function and call it by the Spring controller. The first time works fine and returned right info. However, when I invoked it the second time, it will cause java.io.InterruptedIOException: executor rejected. What happened?
```
HmacSignatureGenerator signatureGenerator = new HmacSignatureGenerator(accountDetail.getSecretKey());
        WebSocketApiClient client = new WebSocketApiClientImpl(accountDetail.getApiKey(), signatureGenerator, DefaultUrls.WS_API_URL);
        final int waitTime = 5000;
        System.out.println(Thread.currentThread().getName());
        client.connect(((event) -> {
            System.out.println(event);
        }));

        client.account().accountTradeHistory("BTCUSDT", null);
        try {
            Thread.sleep(waitTime);
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            client.close();
        }
        client = null;
```

Error:
```
java.io.InterruptedIOException: executor rejected
	at okhttp3.internal.connection.RealCall$AsyncCall.executeOn(RealCall.kt:501) ~[okhttp-4.9.3.jar:na]
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:184) ~[okhttp-4.9.3.jar:na]
	at okhttp3.Dispatcher.enqueue$okhttp(Dispatcher.kt:125) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall.enqueue(RealCall.kt:164) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.ws.RealWebSocket.connect(RealWebSocket.kt:165) ~[okhttp-4.9.3.jar:na]
	at okhttp3.OkHttpClient.newWebSocket(OkHttpClient.kt:281) ~[okhttp-4.9.3.jar:na]
	at com.binance.connector.client.utils.WebSocketConnection.connect(WebSocketConnection.java:66) ~[binance-connector-java-3.0.0rc3.jar:na]
	at com.binance.connector.client.impl.WebSocketApiClientImpl.connect(WebSocketApiClientImpl.java:93) ~[binance-connector-java-3.0.0rc3.jar:na]
	at com.binance.connector.client.impl.WebSocketApiClientImpl.connect(WebSocketApiClientImpl.java:84) ~[binance-connector-java-3.0.0rc3.jar:na]
	at com.cryptotal.service.core.service.BinanceUtils.getTransactionAsync(BinanceUtils.java:19) ~[classes/:na]
```

**Comment by jasonyl13579** [comment]
The error happened at line 19: client.connect(((event) -> {

**Comment by aisling-2** [comment]
Hi @jasonyl13579, 
The `java.io.InterruptedIOException` exception is usually thrown when a thread is interrupted while performing an I/O operation. In this case, the interruption is happening when the WebSocketApiClient is attempting to connect. Reasons might be:

Network or Connectivity Issues: WebSocket server connection fails due to network issues or connectivity problems (firewall restrictions, proxy settings, or a temporary server outage).

Threading Issue: The interrupt might be caused by a separate thread interrupting the main thread, possibly during the Thread.sleep(waitTime) operation.

**Comment by jasonyl13579** [comment]
Hi, what would be the reason that this error does not happen at first and occur at the second call? would it be possible that somehow the WebSocketApiClient does not close the connection properly at the first time?

**Comment by jasonyl13579** [comment]
hello, I just found this post
 https://stackoverflow.com/questions/70833959/okhttp-websocket-rejectedexecutionexception-when-try-to-restart
I think it might be the problem in your  WebSocketClientImpl.class
  public void close() {
        this.connection.close();
       -> client.dispatcher().executorService().shutdown();
    }

Would you mind confirm this?

**Comment by aisling-2** [comment]
Hi @jasonyl13579 I'm not able to reproduce your error and so far, we haven't got another report mentioning a similar issue so far. So, I would like to double check and see what's your situation now?

**Comment by aisling-2** [comment]
Due to inactivity, we're closing this issue.
However, please feel free to re-open whoever also has the same issue, there's reproducible steps or there's a proposed solution.
